### ISSUE TITLE
Add konsole to proc_name list

### ISSUE THREAD

**Issue by vasa1** [leehblue/texpander#14]
Hi,

I use Kubuntu 16.04 and so I modified 

    if [[ $proc_name =~ (termin|nano) ]]

to

    if [[ $proc_name =~ (termin|nano|konsole) ]]

If you feel it's helpful, please add `konsole` to your code.

Thanks,
vasa1

**Comment by leehblue** [comment]
Thanks for the recommendation. I just added `konsole` to the terminal check.
