### ISSUE TITLE
order of snippets

### ISSUE THREAD

**Issue by rwijtvliet** [leehblue/texpander#32]
The order in which the snippets appear in the pop-up window is counterintuitive. 

E.g., I have a snippet called "em.txt" and one called "emg.txt". I'd expect the first one to appear first, but it doesn't - so when I type 'em' and press Enter, it actually inserts the contents of emg.txt.

**Comment by leehblue** [comment]
The order of the files is the same as it would be if you list the files using the `ls` command.
