### ISSUE TITLE
Update usage example for zenity list

### ISSUE THREAD

**Issue by yafp** [leehblue/texpander#7]
The usage example in README.md should be updated after switching to zenity list

**Comment by PabloDinella** [comment]
I made a GIF as a demo, it's pretty low quality though... Maybe it's a good ideia to put on README?

![untitled](https://cloud.githubusercontent.com/assets/2482730/20525967/140efa6e-b0a9-11e6-9026-4decbee0d07e.gif)

**Comment by yafp** [comment]
Good idea - but i would skip the idea of showing your keyboard-presses - as the keyboard-combination is user-specific and might be misleading like that.

Lets see what @leehblue responds

**Comment by leehblue** [comment]
This is great! Thanks so much for putting this together! I'll add this to the README along with an explanation that the keyboard shortcuts are customizable. I'll also describe how to set your own keyboard shortcuts to further underscore the point that you have to link the shortcuts to the texpander script for any of this to work. Does that sound like a good plan to you guys?

**Comment by yafp** [comment]
@leehblue for sure

**Comment by kek91** [comment]
The gif image doesn't appear correctly in your README.md

Direct link: 
https://camo.githubusercontent.com/a55fe476e5b88f50d64fccab803023cdd66e303d/68747470733a2f2f6c65652e626c75652f73686172652f74657870616e6465722d64656d6f2e676966

Gives error message: `Content length exceeded`

**Comment by leehblue** [comment]
Yeah, I know. I'm not sure exactly why that is. I _think_ it is because of a file size limit of 5MB for images in readme files. I haven't confirmed this though.
